<?php
/**
 * ContractPeer - Terms of Service
 * Tailored to actual business practices.
 */
require_once __DIR__ . '/../includes/config.php';
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Service — ContractPeer</title>
    <link rel="stylesheet" href="/assets/css/style.css">
    <style>
        .legal-doc { max-width: 800px; margin: 0 auto; padding: 60px 24px; line-height: 1.7; }
        .legal-doc h1 { margin-bottom: 8px; }
        .legal-doc .updated { color: var(--gray-400); margin-bottom: 32px; }
        .legal-doc h2 { margin-top: 32px; margin-bottom: 8px; }
        .legal-doc p { margin-bottom: 12px; color: var(--gray-700); }
        .legal-doc ul { margin-bottom: 12px; padding-left: 24px; }
        .legal-doc li { margin-bottom: 6px; color: var(--gray-700); }
    </style>
</head>
<body>
<nav class="nav">
    <div class="container nav-inner">
        <a href="/" class="nav-logo">Contract<span>Peer</span></a>
        <button class="mobile-menu-toggle" onclick="document.getElementById('mobileMenu').classList.toggle('open')">☰</button>
        <div class="nav-links">
            <a href="/login.php">Sign In</a>
            <a href="/register.php" class="nav-cta">Start Free Trial</a>
        </div>
    </div>
</nav>
<div class="mobile-menu" id="mobileMenu">
    <a href="/#features">Features</a>
    <a href="/free-nda-check.php">Free NDA Check</a>
    <a href="/pricing.php">Pricing</a>
    <a href="/blog/">Blog</a>
    <a href="/login.php">Sign In</a>
    <a href="/register.php" class="nav-cta">Start Free Trial</a>
</div>

<div class="legal-doc">
<h1>Terms of Service</h1>
<p class="updated">Last updated: July 22, 2026</p>

<p>These Terms of Service ("Terms") govern your use of ContractPeer, a web-based AI contract analysis tool, operated by Contract Peer (contractpeer.com). By creating an account or using the Service, you agree to these Terms.</p>

<h2>1. The Service</h2>
<p>ContractPeer provides AI-assisted contract analysis. You upload contracts (PDF, DOCX, or TXT files), and the Service analyzes them to identify potential risks, provide plain-language explanations, and suggest revisions. The Service is a <strong>decision-support tool</strong>, not a legal service.</p>

<h2>2. Not Legal Advice</h2>
<p><strong>ContractPeer does not provide legal advice.</strong> The analysis produced by the Service is for informational purposes only. It does not constitute legal advice, does not create an attorney-client relationship, and should not be relied upon as the sole basis for legal decisions. You are responsible for having a qualified attorney review any contract before making decisions. The Service may identify risks that are not present or fail to identify risks that are present.</p>

<h2>3. No Unauthorized Practice of Law</h2>
<p>ContractPeer is software, not a law firm or legal service provider. It does not draft legal documents, represent clients, or provide legal opinions. The AI analysis is generated by automated language models and is not reviewed by a licensed attorney before being presented to you.</p>

<h2>4. Accounts</h2>
<p>You must provide a valid email address and create a password to use the Service. You are responsible for maintaining the security of your account and password. You must be at least 18 years old to use the Service. If you are using the Service on behalf of a law firm or company, you represent that you have authority to bind that entity.</p>

<h2>5. Subscriptions and Billing</h2>
<ul>
    <li><strong>Free Trial:</strong> New accounts receive a 14-day free trial with 3 contract analyses. No credit card is required to start a trial.</li>
    <li><strong>Paid Plans:</strong> After the trial, you may subscribe to a paid plan (Starter at $49/mo, Professional at $99/mo, or Firm at $199/mo). Plans are billed monthly through Stripe.</li>
    <li><strong>Taxes:</strong> Applicable sales tax or VAT is calculated and collected automatically at checkout.</li>
    <li><strong>Cancellation:</strong> You may cancel your subscription at any time. Cancellation takes effect at the end of your current billing period. No further charges will occur after cancellation.</li>
    <li><strong>Fee Changes:</strong> We may change pricing with at least 30 days' notice. Existing subscribers will be charged the new rate at the next billing cycle after the notice period.</li>
</ul>

<h2>6. Acceptable Use</h2>
<p>You agree not to:</p>
<ul>
    <li>Upload contracts that you do not have the right to upload;</li>
    <li>Use the Service to engage in any unlawful activity;</li>
    <li>Attempt to reverse-engineer, decompile, or otherwise extract the Service's underlying technology;</li>
    <li>Share your account credentials with others (team seats are available on the Firm plan);</li>
    <li>Use the Service in a way that could damage, disable, or impair the Service.</li>
</ul>

<h2>7. Your Content</h2>
<p>You retain ownership of the contracts you upload. You grant ContractPeer a limited license to process your contracts solely for the purpose of providing the analysis. Your contract text is not used to train AI models. See our <a href="/legal/privacy.php">Privacy Policy</a> for details on data handling.</p>

<h2>8. Confidentiality</h2>
<p>We understand that contracts contain sensitive and confidential information. Contracts are processed to generate analysis and the extracted text may be stored temporarily. We do not share your contract data with third parties. Uploaded files are deleted after processing; analysis results (without the full contract text) are stored in your account history.</p>

<h2>9. Intellectual Property</h2>
<p>ContractPeer, including its software, design, risk taxonomy, and analysis methodology, is the intellectual property of Contract Peer. You may not copy, modify, or distribute the Service without permission. The analysis output provided to you may be used for your internal legal review purposes.</p>

<h2>10. Disclaimers</h2>
<p>The Service is provided "as is" and "as available" without warranties of any kind, whether express or implied. We do not warrant that the Service will be error-free, that analysis results will be accurate, or that the Service will meet your specific requirements. AI-generated analysis may contain errors or omissions.</p>

<h2>11. Limitation of Liability</h2>
<p>To the maximum extent permitted by law, Contract Peer shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to legal decisions made based on the analysis. Our total liability shall not exceed the amount you paid for the Service in the 12 months preceding the claim.</p>

<h2>12. Indemnification</h2>
<p>You agree to indemnify and hold harmless Contract Peer from any claims arising from your use of the Service, including claims by your clients related to contract review decisions made based on the Service's analysis.</p>

<h2>13. Termination</h2>
<p>You may delete your account at any time from the Account page, which permanently deletes all your data. We may suspend or terminate your account if you violate these Terms.</p>

<h2>14. Governing Law</h2>
<p>These Terms are governed by applicable law in the jurisdiction where Contract Peer operates. Disputes will be resolved in the appropriate courts of that jurisdiction.</p>

<h2>15. Changes to These Terms</h2>
<p>We may update these Terms from time to time. Material changes will be notified by email. Continued use after changes take effect constitutes acceptance.</p>

<h2>16. Contact</h2>
<p>For questions about these Terms, contact us at <?= htmlspecialchars(SUPPORT_EMAIL) ?>.</p>

<p style="margin-top: 48px; font-size: 0.85rem; color: var(--gray-400); font-style: italic;">
    These Terms were generated for ContractPeer and have not been reviewed by an attorney. They should be reviewed by qualified counsel before reliance.
</p>
</div>

<?php include __DIR__ . '/../templates/footer.php'; ?>
</body>
</html>
